spring:
  datasource:
    #Driver
    driver-class-name: com.mysql.jdbc.Driver
    #数据库链接
    url: jdbc:mysql://localhost:3306/XMLN?useUnicode=true&characterEncoding=UTF-8&useSSL=false";
    #帐号
    username: xmln
    #密码
    password: Xmln123.

    #初始连接数
    #initialSize: 5
    #最小连接池数量
    #minIdle: 5
    #最大连接池数量
    #maxActive: 50
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    #maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #timeBetweenEvictionRunsMillis: 60000
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    #testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    #testOnReturn: false
    #此项配置为true即可，不影响性能，并且保证安全性。意义为：申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    #testWhileIdle: true
